<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Comparación de Modelos | index.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.45 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Comparación de Modelos | index.knit" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Comparación de Modelos | index.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="prophet.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>



<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="contexto.html"><a href="contexto.html"><i class="fa fa-check"></i><b>1</b> Contexto</a>
<ul>
<li class="chapter" data-level="1.1" data-path="contexto.html"><a href="contexto.html#importancia-del-pron%C3%B3stico-hidrometeorol%C3%B3gico-en-la-gesti%C3%B3n-del-riesgo"><i class="fa fa-check"></i><b>1.1</b> Importancia del pronóstico hidrometeorológico en la gestión del riesgo</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="contexto.html"><a href="contexto.html#anticipaci%C3%B3n-y-reducci%C3%B3n-de-impactos"><i class="fa fa-check"></i><b>1.1.1</b> Anticipación y reducción de impactos</a></li>
<li class="chapter" data-level="1.1.2" data-path="contexto.html"><a href="contexto.html#apoyo-a-la-planificaci%C3%B3n-territorial-y-ambiental"><i class="fa fa-check"></i><b>1.1.2</b> Apoyo a la planificación territorial y ambiental</a></li>
<li class="chapter" data-level="1.1.3" data-path="contexto.html"><a href="contexto.html#fortalecimiento-de-la-gesti%C3%B3n-del-recurso-h%C3%ADdrico-y-la-sostenibilidad"><i class="fa fa-check"></i><b>1.1.3</b> Fortalecimiento de la gestión del recurso hídrico y la sostenibilidad</a></li>
<li class="chapter" data-level="1.1.4" data-path="contexto.html"><a href="contexto.html#valor-agregado-del-pron%C3%B3stico-para-la-gesti%C3%B3n-del-riesgo"><i class="fa fa-check"></i><b>1.1.4</b> Valor agregado del pronóstico para la gestión del riesgo</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="contexto.html"><a href="contexto.html#propuesta-de-informaci%C3%B3n-a-trabajar-pron%C3%B3stico-de-variables-hidrometeorol%C3%B3gicas-para-la-gesti%C3%B3n-del-riesgo-en-el-valle-del-cauca"><i class="fa fa-check"></i><b>1.2</b> Propuesta de información a trabajar: Pronóstico de variables hidrometeorológicas para la gestión del riesgo en el Valle del Cauca</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i><b>2</b> Referencias</a></li>
<li class="chapter" data-level="3" data-path="preparacion.html"><a href="preparacion.html"><i class="fa fa-check"></i><b>3</b> Preparación de Datos y Modelos</a>
<ul>
<li class="chapter" data-level="3.1" data-path="preparacion.html"><a href="preparacion.html#carga-de-librer%C3%ADas"><i class="fa fa-check"></i><b>3.1</b> Carga de Librerías</a></li>
<li class="chapter" data-level="3.2" data-path="preparacion.html"><a href="preparacion.html#lectura-y-limpieza-de-datos"><i class="fa fa-check"></i><b>3.2</b> Lectura y Limpieza de Datos</a></li>
<li class="chapter" data-level="3.3" data-path="preparacion.html"><a href="preparacion.html#interpolaci%C3%B3n-de-valores-faltantes"><i class="fa fa-check"></i><b>3.3</b> Interpolación de Valores Faltantes</a></li>
<li class="chapter" data-level="3.4" data-path="preparacion.html"><a href="preparacion.html#creaci%C3%B3n-de-series-temporales"><i class="fa fa-check"></i><b>3.4</b> Creación de Series Temporales</a></li>
<li class="chapter" data-level="3.5" data-path="preparacion.html"><a href="preparacion.html#partici%C3%B3n-traintest"><i class="fa fa-check"></i><b>3.5</b> Partición Train/Test</a></li>
<li class="chapter" data-level="3.6" data-path="preparacion.html"><a href="preparacion.html#ajuste-del-modelo-holt-winters"><i class="fa fa-check"></i><b>3.6</b> Ajuste del Modelo Holt-Winters</a></li>
<li class="chapter" data-level="3.7" data-path="preparacion.html"><a href="preparacion.html#ajuste-del-modelo-sarima"><i class="fa fa-check"></i><b>3.7</b> Ajuste del Modelo SARIMA</a></li>
<li class="chapter" data-level="3.8" data-path="preparacion.html"><a href="preparacion.html#ajuste-del-modelo-prophet"><i class="fa fa-check"></i><b>3.8</b> Ajuste del Modelo Prophet</a></li>
<li class="chapter" data-level="3.9" data-path="preparacion.html"><a href="preparacion.html#resumen-de-objetos-creados"><i class="fa fa-check"></i><b>3.9</b> Resumen de Objetos Creados</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html"><i class="fa fa-check"></i><b>4</b> Análisis Exploratorio de Series de Tiempo</a>
<ul>
<li class="chapter" data-level="4.1" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#visualizaci%C3%B3n-de-series-temporales"><i class="fa fa-check"></i><b>4.1</b> Visualización de Series Temporales</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#serie-temporal-de-precipitaci%C3%B3n-mensual"><i class="fa fa-check"></i><b>4.1.1</b> Serie Temporal de Precipitación Mensual</a></li>
<li class="chapter" data-level="4.1.2" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#visualizaci%C3%B3n-por-a%C3%B1os"><i class="fa fa-check"></i><b>4.1.2</b> Visualización por Años</a></li>
<li class="chapter" data-level="4.1.3" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#visualizaci%C3%B3n-de-patrones-normalizados-por-a%C3%B1o"><i class="fa fa-check"></i><b>4.1.3</b> Visualización de Patrones Normalizados por Año</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#an%C3%A1lisis-de-autocorrelaci%C3%B3n-y-rezagos"><i class="fa fa-check"></i><b>4.2</b> Análisis de Autocorrelación y Rezagos</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#gr%C3%A1ficos-de-lag-rezagos"><i class="fa fa-check"></i><b>4.2.1</b> Gráficos de Lag (Rezagos)</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#prueba-de-estacionariedad"><i class="fa fa-check"></i><b>4.3</b> Prueba de Estacionariedad</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#test-de-dickey-fuller-aumentado-adf"><i class="fa fa-check"></i><b>4.3.1</b> Test de Dickey-Fuller Aumentado (ADF)</a></li>
<li class="chapter" data-level="4.3.2" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#an%C3%A1lisis-acf-y-pacf-de-la-serie-original"><i class="fa fa-check"></i><b>4.3.2</b> Análisis ACF y PACF de la Serie Original</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#an%C3%A1lisis-de-promedios-m%C3%B3viles"><i class="fa fa-check"></i><b>4.4</b> Análisis de Promedios Móviles</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#promedios-m%C3%B3viles-de-diferentes-%C3%B3rdenes"><i class="fa fa-check"></i><b>4.4.1</b> Promedios Móviles de Diferentes Órdenes</a></li>
<li class="chapter" data-level="4.4.2" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#descomposici%C3%B3n-de-la-serie-temporal"><i class="fa fa-check"></i><b>4.4.2</b> Descomposición de la Serie Temporal</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="holt-winters.html"><a href="holt-winters.html"><i class="fa fa-check"></i><b>5</b> Suavizamiento Exponencial: Método Holt-Winters</a>
<ul>
<li class="chapter" data-level="5.1" data-path="holt-winters.html"><a href="holt-winters.html#resumen-del-modelo-ajustado"><i class="fa fa-check"></i><b>5.1</b> Resumen del Modelo Ajustado</a></li>
<li class="chapter" data-level="5.2" data-path="holt-winters.html"><a href="holt-winters.html#modelo-holt-winters-aditivo"><i class="fa fa-check"></i><b>5.2</b> Modelo Holt-Winters Aditivo</a></li>
<li class="chapter" data-level="5.3" data-path="holt-winters.html"><a href="holt-winters.html#an%C3%A1lisis-comparativo-serie-original-vs.-suavizado"><i class="fa fa-check"></i><b>5.3</b> Análisis Comparativo: Serie Original vs. Suavizado</a></li>
<li class="chapter" data-level="5.4" data-path="holt-winters.html"><a href="holt-winters.html#descomposici%C3%B3n-de-la-serie-suavizada"><i class="fa fa-check"></i><b>5.4</b> Descomposición de la Serie Suavizada</a></li>
<li class="chapter" data-level="5.5" data-path="holt-winters.html"><a href="holt-winters.html#pron%C3%B3stico-para-el-per%C3%ADodo-de-prueba"><i class="fa fa-check"></i><b>5.5</b> Pronóstico para el Período de Prueba</a></li>
<li class="chapter" data-level="5.6" data-path="holt-winters.html"><a href="holt-winters.html#evaluaci%C3%B3n-del-desempe%C3%B1o-del-modelo"><i class="fa fa-check"></i><b>5.6</b> Evaluación del Desempeño del Modelo</a></li>
<li class="chapter" data-level="5.7" data-path="holt-winters.html"><a href="holt-winters.html#an%C3%A1lisis-de-residuos-del-pron%C3%B3stico"><i class="fa fa-check"></i><b>5.7</b> Análisis de Residuos del Pronóstico</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sarima.html"><a href="sarima.html"><i class="fa fa-check"></i><b>6</b> Modelado ARIMA: Metodología Box-Jenkins</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sarima.html"><a href="sarima.html#resumen-del-modelo-ajustado-1"><i class="fa fa-check"></i><b>6.1</b> Resumen del Modelo Ajustado</a></li>
<li class="chapter" data-level="6.2" data-path="sarima.html"><a href="sarima.html#especificaci%C3%B3n-del-modelo-sarima"><i class="fa fa-check"></i><b>6.2</b> Especificación del Modelo SARIMA</a></li>
<li class="chapter" data-level="6.3" data-path="sarima.html"><a href="sarima.html#an%C3%A1lisis-comparativo-serie-original-vs.-valores-ajustados"><i class="fa fa-check"></i><b>6.3</b> Análisis Comparativo: Serie Original vs. Valores Ajustados</a></li>
<li class="chapter" data-level="6.4" data-path="sarima.html"><a href="sarima.html#interpretaci%C3%B3n-de-componentes-del-modelo"><i class="fa fa-check"></i><b>6.4</b> Interpretación de Componentes del Modelo</a></li>
<li class="chapter" data-level="6.5" data-path="sarima.html"><a href="sarima.html#diagn%C3%B3stico-de-residuos"><i class="fa fa-check"></i><b>6.5</b> Diagnóstico de Residuos</a></li>
<li class="chapter" data-level="6.6" data-path="sarima.html"><a href="sarima.html#pron%C3%B3stico-para-1998"><i class="fa fa-check"></i><b>6.6</b> Pronóstico para 1998</a></li>
<li class="chapter" data-level="6.7" data-path="sarima.html"><a href="sarima.html#evaluaci%C3%B3n-del-desempe%C3%B1o-del-modelo-1"><i class="fa fa-check"></i><b>6.7</b> Evaluación del Desempeño del Modelo</a></li>
<li class="chapter" data-level="6.8" data-path="sarima.html"><a href="sarima.html#diagn%C3%B3stico-de-errores-de-pron%C3%B3stico"><i class="fa fa-check"></i><b>6.8</b> Diagnóstico de Errores de Pronóstico</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="prophet.html"><a href="prophet.html"><i class="fa fa-check"></i><b>7</b> Enfoque de Regresión: Facebook Prophet</a>
<ul>
<li class="chapter" data-level="7.1" data-path="prophet.html"><a href="prophet.html#series-temporales-como-regresi%C3%B3n"><i class="fa fa-check"></i><b>7.1</b> Series Temporales como Regresión</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="prophet.html"><a href="prophet.html#paradigma-tradicional-vs.-enfoque-regresivo"><i class="fa fa-check"></i><b>7.1.1</b> Paradigma Tradicional vs. Enfoque Regresivo</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="prophet.html"><a href="prophet.html#resumen-del-modelo-ajustado-2"><i class="fa fa-check"></i><b>7.2</b> Resumen del Modelo Ajustado</a></li>
<li class="chapter" data-level="7.3" data-path="prophet.html"><a href="prophet.html#extracci%C3%B3n-y-visualizaci%C3%B3n-de-componentes"><i class="fa fa-check"></i><b>7.3</b> Extracción y Visualización de Componentes</a></li>
<li class="chapter" data-level="7.4" data-path="prophet.html"><a href="prophet.html#an%C3%A1lisis-comparativo-serie-original-vs.-valores-ajustados-1"><i class="fa fa-check"></i><b>7.4</b> Análisis Comparativo: Serie Original vs. Valores Ajustados</a></li>
<li class="chapter" data-level="7.5" data-path="prophet.html"><a href="prophet.html#pron%C3%B3stico-para-1998-1"><i class="fa fa-check"></i><b>7.5</b> Pronóstico para 1998</a></li>
<li class="chapter" data-level="7.6" data-path="prophet.html"><a href="prophet.html#evaluaci%C3%B3n-del-desempe%C3%B1o"><i class="fa fa-check"></i><b>7.6</b> Evaluación del Desempeño</a></li>
<li class="chapter" data-level="7.7" data-path="prophet.html"><a href="prophet.html#diagn%C3%B3stico-de-residuos-1"><i class="fa fa-check"></i><b>7.7</b> Diagnóstico de Residuos</a></li>
<li class="chapter" data-level="7.8" data-path="prophet.html"><a href="prophet.html#diagn%C3%B3stico-de-errores-de-pron%C3%B3stico-1"><i class="fa fa-check"></i><b>7.8</b> Diagnóstico de Errores de Pronóstico</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="comparacion.html"><a href="comparacion.html"><i class="fa fa-check"></i><b>8</b> Comparación de Modelos</a>
<ul>
<li class="chapter" data-level="8.1" data-path="comparacion.html"><a href="comparacion.html#introducci%C3%B3n-tres-paradigmas"><i class="fa fa-check"></i><b>8.1</b> Introducción: Tres Paradigmas</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="comparacion.html"><a href="comparacion.html#holt-winters-suavizamiento-exponencial"><i class="fa fa-check"></i><b>8.1.1</b> Holt-Winters: Suavizamiento Exponencial</a></li>
<li class="chapter" data-level="8.1.2" data-path="comparacion.html"><a href="comparacion.html#sarima-modelado-estoc%C3%A1stico"><i class="fa fa-check"></i><b>8.1.2</b> SARIMA: Modelado Estocástico</a></li>
<li class="chapter" data-level="8.1.3" data-path="comparacion.html"><a href="comparacion.html#prophet-regresi%C3%B3n-aditiva"><i class="fa fa-check"></i><b>8.1.3</b> Prophet: Regresión Aditiva</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="comparacion.html"><a href="comparacion.html#resumen-de-modelos-ajustados"><i class="fa fa-check"></i><b>8.2</b> Resumen de Modelos Ajustados</a></li>
<li class="chapter" data-level="8.3" data-path="comparacion.html"><a href="comparacion.html#tabla-comparativa-de-m%C3%A9tricas"><i class="fa fa-check"></i><b>8.3</b> Tabla Comparativa de Métricas</a></li>
<li class="chapter" data-level="8.4" data-path="comparacion.html"><a href="comparacion.html#visualizaci%C3%B3n-comparativa-de-pron%C3%B3sticos"><i class="fa fa-check"></i><b>8.4</b> Visualización Comparativa de Pronósticos</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="comparacion.html"><a href="comparacion.html#an%C3%A1lisis-visual"><i class="fa fa-check"></i><b>8.4.1</b> Análisis Visual</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="comparacion.html"><a href="comparacion.html#comparaci%C3%B3n-conceptual"><i class="fa fa-check"></i><b>8.5</b> Comparación Conceptual</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="comparacion" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Comparación de Modelos<a href="comparacion.html#comparacion" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este capítulo se realiza una <strong>comparación integral</strong> de los tres enfoques de pronóstico aplicados a la precipitación mensual en Cali:</p>
<ol style="list-style-type: decimal">
<li><strong>Holt-Winters</strong> (Capítulo <a href="holt-winters.html#holt-winters">5</a>): Suavizamiento exponencial</li>
<li><strong>SARIMA</strong> (Capítulo <a href="sarima.html#sarima">6</a>): Modelo estocástico Box-Jenkins</li>
<li><strong>Prophet</strong> (Capítulo <a href="prophet.html#prophet">7</a>): Modelo aditivo generalizado (regresión)</li>
</ol>
<p>El objetivo es evaluar cuál método ofrece el mejor desempeño para este caso específico, considerando métricas cuantitativas, interpretabilidad y aplicabilidad práctica.</p>
<div id="introducción-tres-paradigmas" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Introducción: Tres Paradigmas<a href="comparacion.html#introducci%C3%B3n-tres-paradigmas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Cada modelo representa una <strong>filosofía distinta</strong> para abordar series temporales:</p>
<div id="holt-winters-suavizamiento-exponencial" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Holt-Winters: Suavizamiento Exponencial<a href="comparacion.html#holt-winters-suavizamiento-exponencial" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Concepto central:</strong>
- Promedios ponderados con pesos que decaen exponencialmente
- Captura nivel, tendencia y estacionalidad mediante ecuaciones recursivas
- Énfasis en observaciones recientes</p>
<p><strong>Ventajas:</strong>
- Simplicidad conceptual e interpretativa
- Rápido ajuste y cómputo
- Efectivo para patrones estacionales estables</p>
<p><strong>Limitaciones:</strong>
- Intervalos de confianza menos rigurosos que ARIMA
- No captura autocorrelación residual compleja
- Requiere estacionariedad aproximada</p>
</div>
<div id="sarima-modelado-estocástico" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> SARIMA: Modelado Estocástico<a href="comparacion.html#sarima-modelado-estoc%C3%A1stico" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Concepto central:</strong>
- Serie como proceso autorregresivo y de medias móviles
- Modelado explícito de autocorrelación temporal
- Fundamentación en teoría probabilística</p>
<p><strong>Ventajas:</strong>
- Base estadística rigurosa (Box-Jenkins)
- Intervalos de confianza bien calibrados
- Captura dependencias temporales complejas</p>
<p><strong>Limitaciones:</strong>
- Requiere identificación de órdenes (p, d, q)
- Sensible a outliers y valores faltantes
- Coeficientes menos interpretables</p>
</div>
<div id="prophet-regresión-aditiva" class="section level3 hasAnchor" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> Prophet: Regresión Aditiva<a href="comparacion.html#prophet-regresi%C3%B3n-aditiva" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Concepto central:</strong>
- Descomposición en componentes interpretables
- Tendencia + estacionalidad + eventos + error
- Modelado como regresión con predictores temporales</p>
<p><strong>Ventajas:</strong>
- Componentes visualmente interpretables
- Robusto a datos irregulares y outliers
- Fácil incorporación de regresores externos</p>
<p><strong>Limitaciones:</strong>
- Menos fundamentación teórica tradicional
- Puede ser excesivo para series simples
- Requiere ajuste de hiperparámetros</p>
<p><strong>Nota</strong>: Todos los modelos fueron ajustados en el Capítulo <a href="preparacion.html#preparacion">3</a>. Los objetos <code>hw_model</code>, <code>sarima_model</code>, <code>prophet_model</code> y sus métricas están disponibles directamente.</p>
</div>
</div>
<div id="resumen-de-modelos-ajustados" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Resumen de Modelos Ajustados<a href="comparacion.html#resumen-de-modelos-ajustados" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>## === MODELOS PARA COMPARACIÓN ===</code></pre>
<pre><code>## 1. HOLT-WINTERS</code></pre>
<pre><code>##    Parámetros: α = 0.0921 | β = 0.0378 | γ = 0.3005</code></pre>
<pre><code>## 2. SARIMA</code></pre>
<pre><code>##    Orden: SARIMA(3,0,0)(1,0,1)[12]</code></pre>
<pre><code>## 3. PROPHET</code></pre>
<pre><code>##    Changepoints detectados: 25</code></pre>
<pre><code>##    Modo: Aditivo | Estacionalidad: Fourier anual</code></pre>
</div>
<div id="tabla-comparativa-de-métricas" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> Tabla Comparativa de Métricas<a href="comparacion.html#tabla-comparativa-de-m%C3%A9tricas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<table>
<caption><span id="tab:tabla-metricas">Table 8.1: </span>Comparación de métricas de pronóstico para 1998 (12 meses)</caption>
<thead>
<tr class="header">
<th align="left">Modelo</th>
<th align="right">MAE</th>
<th align="right">RMSE</th>
<th align="right">MAPE</th>
<th align="right">Cobertura IC (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Holt-Winters</td>
<td align="right">4.016</td>
<td align="right">4.585</td>
<td align="right">399.27</td>
<td align="right">100.0</td>
</tr>
<tr class="even">
<td align="left">SARIMA</td>
<td align="right">4.067</td>
<td align="right">5.036</td>
<td align="right">383.01</td>
<td align="right">91.7</td>
</tr>
<tr class="odd">
<td align="left">Prophet</td>
<td align="right">4.171</td>
<td align="right">4.810</td>
<td align="right">353.11</td>
<td align="right">100.0</td>
</tr>
</tbody>
</table>
<p>=== RANKINGS POR MÉTRICA (1 = Mejor) ===</p>
<p>Error Absoluto Medio (MAE):
1. Holt-Winters - 4.016 mm
2. SARIMA - 4.067 mm
3. Prophet - 4.171 mm</p>
<p>Raíz del Error Cuadrático Medio (RMSE):
1. Holt-Winters - 4.585 mm
2. Prophet - 4.81 mm
3. SARIMA - 5.036 mm</p>
<p>Error Porcentual Absoluto Medio (MAPE):
1. Prophet - 353.11%
2. SARIMA - 383.01%
3. Holt-Winters - 399.27%</p>
<blockquote>
<blockquote>
<blockquote>
<p>MODELO CON MEJOR DESEMPEÑO GENERAL: Prophet &lt;&lt;&lt;</p>
</blockquote>
</blockquote>
</blockquote>
</div>
<div id="visualización-comparativa-de-pronósticos" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> Visualización Comparativa de Pronósticos<a href="comparacion.html#visualizaci%C3%B3n-comparativa-de-pron%C3%B3sticos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="index_files/figure-html/grafico-comparacion-modelos-1.png" width="1344" /></p>
<div id="análisis-visual" class="section level3 hasAnchor" number="8.4.1">
<h3><span class="header-section-number">8.4.1</span> Análisis Visual<a href="comparacion.html#an%C3%A1lisis-visual" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Del gráfico anterior se observa:</p>
<p><strong>Similitud general:</strong>
- Los tres modelos capturan el patrón estacional bimodal
- Picos en abril-mayo y octubre-noviembre bien identificados
- Diferencias sutiles entre pronósticos</p>
<p><strong>Intervalos de confianza:</strong>
- Prophet: Intervalos más amplios (más conservadores)
- SARIMA: Intervalos intermedios
- Holt-Winters: Intervalos más estrechos</p>
<p><strong>Desviaciones notables:</strong>
- Meses con mayor discrepancia entre modelos: Marzo, Julio
- Todos los modelos capturan razonablemente la temporada seca (julio-agosto)</p>
</div>
</div>
<div id="comparación-conceptual" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> Comparación Conceptual<a href="comparacion.html#comparaci%C3%B3n-conceptual" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<table>
<caption><span id="tab:tabla-conceptual">Table 8.2: </span>Comparación conceptual de los tres enfoques</caption>
<colgroup>
<col width="21%" />
<col width="32%" />
<col width="22%" />
<col width="23%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Aspecto</th>
<th align="left">Holt-Winters</th>
<th align="left">SARIMA</th>
<th align="left">Prophet</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Paradigma</td>
<td align="left">Suavizamiento exponencial</td>
<td align="left">Proceso estocástico</td>
<td align="left">Regresión aditiva (GAM)</td>
</tr>
<tr class="even">
<td align="left">Manejo de tendencia</td>
<td align="left">Tendencia lineal suavizada</td>
<td align="left">Diferenciación (d, D)</td>
<td align="left">Piecewise linear con changepoints</td>
</tr>
<tr class="odd">
<td align="left">Modelado de estacionalidad</td>
<td align="left">Factores estacionales aditivos/multiplicativos</td>
<td align="left">AR/MA estacional con periodo s</td>
<td align="left">Series de Fourier flexibles</td>
</tr>
<tr class="even">
<td align="left">Datos faltantes</td>
<td align="left">Requiere imputación previa</td>
<td align="left">Problemático (interrumpe serie)</td>
<td align="left">Manejo automático</td>
</tr>
<tr class="odd">
<td align="left">Robustez ante outliers</td>
<td align="left">Moderada</td>
<td align="left">Baja (muy sensible)</td>
<td align="left">Alta (robusto)</td>
</tr>
<tr class="even">
<td align="left">Interpretabilidad</td>
<td align="left">Alta (componentes claros)</td>
<td align="left">Moderada (coeficientes técnicos)</td>
<td align="left">Muy alta (componentes visuales)</td>
</tr>
<tr class="odd">
<td align="left">Regresores externos</td>
<td align="left">No soporta nativamente</td>
<td align="left">ARIMAX (requiere experiencia)</td>
<td align="left">add_regressor() (muy simple)</td>
</tr>
<tr class="even">
<td align="left">Fundamentación teórica</td>
<td align="left">Estadística descriptiva</td>
<td align="left">Teoría probabilística rigurosa</td>
<td align="left">Regresión bayesiana</td>
</tr>
<tr class="odd">
<td align="left">Complejidad computacional</td>
<td align="left">Muy baja</td>
<td align="left">Media</td>
<td align="left">Media-alta</td>
</tr>
<tr class="even">
<td align="left">Horizonte de pronóstico óptimo</td>
<td align="left">Corto-mediano plazo (1-12 meses)</td>
<td align="left">Corto plazo (1-6 meses)</td>
<td align="left">Mediano plazo (6-24 meses)</td>
</tr>
</tbody>
</table>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="prophet.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
