<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Modelado ARIMA: Metodología Box-Jenkins | index.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.45 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Modelado ARIMA: Metodología Box-Jenkins | index.knit" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Modelado ARIMA: Metodología Box-Jenkins | index.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="holt-winters.html"/>
<link rel="next" href="prophet.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>



<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="contexto.html"><a href="contexto.html"><i class="fa fa-check"></i><b>1</b> Contexto</a>
<ul>
<li class="chapter" data-level="1.1" data-path="contexto.html"><a href="contexto.html#importancia-del-pron%C3%B3stico-hidrometeorol%C3%B3gico-en-la-gesti%C3%B3n-del-riesgo"><i class="fa fa-check"></i><b>1.1</b> Importancia del pronóstico hidrometeorológico en la gestión del riesgo</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="contexto.html"><a href="contexto.html#anticipaci%C3%B3n-y-reducci%C3%B3n-de-impactos"><i class="fa fa-check"></i><b>1.1.1</b> Anticipación y reducción de impactos</a></li>
<li class="chapter" data-level="1.1.2" data-path="contexto.html"><a href="contexto.html#apoyo-a-la-planificaci%C3%B3n-territorial-y-ambiental"><i class="fa fa-check"></i><b>1.1.2</b> Apoyo a la planificación territorial y ambiental</a></li>
<li class="chapter" data-level="1.1.3" data-path="contexto.html"><a href="contexto.html#fortalecimiento-de-la-gesti%C3%B3n-del-recurso-h%C3%ADdrico-y-la-sostenibilidad"><i class="fa fa-check"></i><b>1.1.3</b> Fortalecimiento de la gestión del recurso hídrico y la sostenibilidad</a></li>
<li class="chapter" data-level="1.1.4" data-path="contexto.html"><a href="contexto.html#valor-agregado-del-pron%C3%B3stico-para-la-gesti%C3%B3n-del-riesgo"><i class="fa fa-check"></i><b>1.1.4</b> Valor agregado del pronóstico para la gestión del riesgo</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="contexto.html"><a href="contexto.html#propuesta-de-informaci%C3%B3n-a-trabajar-pron%C3%B3stico-de-variables-hidrometeorol%C3%B3gicas-para-la-gesti%C3%B3n-del-riesgo-en-el-valle-del-cauca"><i class="fa fa-check"></i><b>1.2</b> Propuesta de información a trabajar: Pronóstico de variables hidrometeorológicas para la gestión del riesgo en el Valle del Cauca</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="preparacion.html"><a href="preparacion.html"><i class="fa fa-check"></i><b>2</b> Preparación de Datos y Modelos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="preparacion.html"><a href="preparacion.html#carga-de-librer%C3%ADas"><i class="fa fa-check"></i><b>2.1</b> Carga de Librerías</a></li>
<li class="chapter" data-level="2.2" data-path="preparacion.html"><a href="preparacion.html#lectura-y-limpieza-de-datos"><i class="fa fa-check"></i><b>2.2</b> Lectura y Limpieza de Datos</a></li>
<li class="chapter" data-level="2.3" data-path="preparacion.html"><a href="preparacion.html#interpolaci%C3%B3n-de-valores-faltantes"><i class="fa fa-check"></i><b>2.3</b> Interpolación de Valores Faltantes</a></li>
<li class="chapter" data-level="2.4" data-path="preparacion.html"><a href="preparacion.html#creaci%C3%B3n-de-series-temporales"><i class="fa fa-check"></i><b>2.4</b> Creación de Series Temporales</a></li>
<li class="chapter" data-level="2.5" data-path="preparacion.html"><a href="preparacion.html#partici%C3%B3n-traintest"><i class="fa fa-check"></i><b>2.5</b> Partición Train/Test</a></li>
<li class="chapter" data-level="2.6" data-path="preparacion.html"><a href="preparacion.html#ajuste-del-modelo-holt-winters"><i class="fa fa-check"></i><b>2.6</b> Ajuste del Modelo Holt-Winters</a></li>
<li class="chapter" data-level="2.7" data-path="preparacion.html"><a href="preparacion.html#ajuste-del-modelo-sarima"><i class="fa fa-check"></i><b>2.7</b> Ajuste del Modelo SARIMA</a></li>
<li class="chapter" data-level="2.8" data-path="preparacion.html"><a href="preparacion.html#ajuste-del-modelo-prophet"><i class="fa fa-check"></i><b>2.8</b> Ajuste del Modelo Prophet</a></li>
<li class="chapter" data-level="2.9" data-path="preparacion.html"><a href="preparacion.html#resumen-de-objetos-creados"><i class="fa fa-check"></i><b>2.9</b> Resumen de Objetos Creados</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html"><i class="fa fa-check"></i><b>3</b> Análisis Exploratorio de Series de Tiempo</a>
<ul>
<li class="chapter" data-level="3.1" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#visualizaci%C3%B3n-de-series-temporales"><i class="fa fa-check"></i><b>3.1</b> Visualización de Series Temporales</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#serie-temporal-de-precipitaci%C3%B3n-mensual"><i class="fa fa-check"></i><b>3.1.1</b> Serie Temporal de Precipitación Mensual</a></li>
<li class="chapter" data-level="3.1.2" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#visualizaci%C3%B3n-por-a%C3%B1os"><i class="fa fa-check"></i><b>3.1.2</b> Visualización por Años</a></li>
<li class="chapter" data-level="3.1.3" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#visualizaci%C3%B3n-de-patrones-normalizados-por-a%C3%B1o"><i class="fa fa-check"></i><b>3.1.3</b> Visualización de Patrones Normalizados por Año</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#an%C3%A1lisis-de-autocorrelaci%C3%B3n-y-rezagos"><i class="fa fa-check"></i><b>3.2</b> Análisis de Autocorrelación y Rezagos</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#gr%C3%A1ficos-de-lag-rezagos"><i class="fa fa-check"></i><b>3.2.1</b> Gráficos de Lag (Rezagos)</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#prueba-de-estacionariedad"><i class="fa fa-check"></i><b>3.3</b> Prueba de Estacionariedad</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#test-de-dickey-fuller-aumentado-adf"><i class="fa fa-check"></i><b>3.3.1</b> Test de Dickey-Fuller Aumentado (ADF)</a></li>
<li class="chapter" data-level="3.3.2" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#an%C3%A1lisis-acf-y-pacf-de-la-serie-original"><i class="fa fa-check"></i><b>3.3.2</b> Análisis ACF y PACF de la Serie Original</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#an%C3%A1lisis-de-promedios-m%C3%B3viles"><i class="fa fa-check"></i><b>3.4</b> Análisis de Promedios Móviles</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#promedios-m%C3%B3viles-de-diferentes-%C3%B3rdenes"><i class="fa fa-check"></i><b>3.4.1</b> Promedios Móviles de Diferentes Órdenes</a></li>
<li class="chapter" data-level="3.4.2" data-path="analisis-exploratorio.html"><a href="analisis-exploratorio.html#descomposici%C3%B3n-de-la-serie-temporal"><i class="fa fa-check"></i><b>3.4.2</b> Descomposición de la Serie Temporal</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="holt-winters.html"><a href="holt-winters.html"><i class="fa fa-check"></i><b>4</b> Suavizamiento Exponencial: Método Holt-Winters</a>
<ul>
<li class="chapter" data-level="4.1" data-path="holt-winters.html"><a href="holt-winters.html#resumen-del-modelo-ajustado"><i class="fa fa-check"></i><b>4.1</b> Resumen del Modelo Ajustado</a></li>
<li class="chapter" data-level="4.2" data-path="holt-winters.html"><a href="holt-winters.html#modelo-holt-winters-aditivo"><i class="fa fa-check"></i><b>4.2</b> Modelo Holt-Winters Aditivo</a></li>
<li class="chapter" data-level="4.3" data-path="holt-winters.html"><a href="holt-winters.html#an%C3%A1lisis-comparativo-serie-original-vs.-suavizado"><i class="fa fa-check"></i><b>4.3</b> Análisis Comparativo: Serie Original vs. Suavizado</a></li>
<li class="chapter" data-level="4.4" data-path="holt-winters.html"><a href="holt-winters.html#descomposici%C3%B3n-de-la-serie-suavizada"><i class="fa fa-check"></i><b>4.4</b> Descomposición de la Serie Suavizada</a></li>
<li class="chapter" data-level="4.5" data-path="holt-winters.html"><a href="holt-winters.html#pron%C3%B3stico-para-el-per%C3%ADodo-de-prueba"><i class="fa fa-check"></i><b>4.5</b> Pronóstico para el Período de Prueba</a></li>
<li class="chapter" data-level="4.6" data-path="holt-winters.html"><a href="holt-winters.html#evaluaci%C3%B3n-del-desempe%C3%B1o-del-modelo"><i class="fa fa-check"></i><b>4.6</b> Evaluación del Desempeño del Modelo</a></li>
<li class="chapter" data-level="4.7" data-path="holt-winters.html"><a href="holt-winters.html#an%C3%A1lisis-de-residuos-del-pron%C3%B3stico"><i class="fa fa-check"></i><b>4.7</b> Análisis de Residuos del Pronóstico</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sarima.html"><a href="sarima.html"><i class="fa fa-check"></i><b>5</b> Modelado ARIMA: Metodología Box-Jenkins</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sarima.html"><a href="sarima.html#resumen-del-modelo-ajustado-1"><i class="fa fa-check"></i><b>5.1</b> Resumen del Modelo Ajustado</a></li>
<li class="chapter" data-level="5.2" data-path="sarima.html"><a href="sarima.html#especificaci%C3%B3n-del-modelo-sarima"><i class="fa fa-check"></i><b>5.2</b> Especificación del Modelo SARIMA</a></li>
<li class="chapter" data-level="5.3" data-path="sarima.html"><a href="sarima.html#an%C3%A1lisis-comparativo-serie-original-vs.-valores-ajustados"><i class="fa fa-check"></i><b>5.3</b> Análisis Comparativo: Serie Original vs. Valores Ajustados</a></li>
<li class="chapter" data-level="5.4" data-path="sarima.html"><a href="sarima.html#interpretaci%C3%B3n-de-componentes-del-modelo"><i class="fa fa-check"></i><b>5.4</b> Interpretación de Componentes del Modelo</a></li>
<li class="chapter" data-level="5.5" data-path="sarima.html"><a href="sarima.html#diagn%C3%B3stico-de-residuos"><i class="fa fa-check"></i><b>5.5</b> Diagnóstico de Residuos</a></li>
<li class="chapter" data-level="5.6" data-path="sarima.html"><a href="sarima.html#pron%C3%B3stico-para-1998"><i class="fa fa-check"></i><b>5.6</b> Pronóstico para 1998</a></li>
<li class="chapter" data-level="5.7" data-path="sarima.html"><a href="sarima.html#evaluaci%C3%B3n-del-desempe%C3%B1o-del-modelo-1"><i class="fa fa-check"></i><b>5.7</b> Evaluación del Desempeño del Modelo</a></li>
<li class="chapter" data-level="5.8" data-path="sarima.html"><a href="sarima.html#diagn%C3%B3stico-de-errores-de-pron%C3%B3stico"><i class="fa fa-check"></i><b>5.8</b> Diagnóstico de Errores de Pronóstico</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="prophet.html"><a href="prophet.html"><i class="fa fa-check"></i><b>6</b> Enfoque de Regresión: Facebook Prophet</a>
<ul>
<li class="chapter" data-level="6.1" data-path="prophet.html"><a href="prophet.html#series-temporales-como-regresi%C3%B3n"><i class="fa fa-check"></i><b>6.1</b> Series Temporales como Regresión</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="prophet.html"><a href="prophet.html#paradigma-tradicional-vs.-enfoque-regresivo"><i class="fa fa-check"></i><b>6.1.1</b> Paradigma Tradicional vs. Enfoque Regresivo</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="prophet.html"><a href="prophet.html#resumen-del-modelo-ajustado-2"><i class="fa fa-check"></i><b>6.2</b> Resumen del Modelo Ajustado</a></li>
<li class="chapter" data-level="6.3" data-path="prophet.html"><a href="prophet.html#extracci%C3%B3n-y-visualizaci%C3%B3n-de-componentes"><i class="fa fa-check"></i><b>6.3</b> Extracción y Visualización de Componentes</a></li>
<li class="chapter" data-level="6.4" data-path="prophet.html"><a href="prophet.html#an%C3%A1lisis-comparativo-serie-original-vs.-valores-ajustados-1"><i class="fa fa-check"></i><b>6.4</b> Análisis Comparativo: Serie Original vs. Valores Ajustados</a></li>
<li class="chapter" data-level="6.5" data-path="prophet.html"><a href="prophet.html#diagn%C3%B3stico-de-residuos-1"><i class="fa fa-check"></i><b>6.5</b> Diagnóstico de Residuos</a></li>
<li class="chapter" data-level="6.6" data-path="prophet.html"><a href="prophet.html#pron%C3%B3stico-para-1998-1"><i class="fa fa-check"></i><b>6.6</b> Pronóstico para 1998</a></li>
<li class="chapter" data-level="6.7" data-path="prophet.html"><a href="prophet.html#evaluaci%C3%B3n-del-desempe%C3%B1o"><i class="fa fa-check"></i><b>6.7</b> Evaluación del Desempeño</a></li>
<li class="chapter" data-level="6.8" data-path="prophet.html"><a href="prophet.html#diagn%C3%B3stico-de-errores-de-pron%C3%B3stico-1"><i class="fa fa-check"></i><b>6.8</b> Diagnóstico de Errores de Pronóstico</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="comparacion.html"><a href="comparacion.html"><i class="fa fa-check"></i><b>7</b> Comparación de Modelos</a>
<ul>
<li class="chapter" data-level="7.1" data-path="comparacion.html"><a href="comparacion.html#introducci%C3%B3n-tres-paradigmas"><i class="fa fa-check"></i><b>7.1</b> Introducción: Tres Paradigmas</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="comparacion.html"><a href="comparacion.html#holt-winters-suavizamiento-exponencial"><i class="fa fa-check"></i><b>7.1.1</b> Holt-Winters: Suavizamiento Exponencial</a></li>
<li class="chapter" data-level="7.1.2" data-path="comparacion.html"><a href="comparacion.html#sarima-modelado-estoc%C3%A1stico"><i class="fa fa-check"></i><b>7.1.2</b> SARIMA: Modelado Estocástico</a></li>
<li class="chapter" data-level="7.1.3" data-path="comparacion.html"><a href="comparacion.html#prophet-regresi%C3%B3n-aditiva"><i class="fa fa-check"></i><b>7.1.3</b> Prophet: Regresión Aditiva</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="comparacion.html"><a href="comparacion.html#resumen-de-modelos-ajustados"><i class="fa fa-check"></i><b>7.2</b> Resumen de Modelos Ajustados</a></li>
<li class="chapter" data-level="7.3" data-path="comparacion.html"><a href="comparacion.html#tabla-comparativa-de-m%C3%A9tricas"><i class="fa fa-check"></i><b>7.3</b> Tabla Comparativa de Métricas</a></li>
<li class="chapter" data-level="7.4" data-path="comparacion.html"><a href="comparacion.html#visualizaci%C3%B3n-comparativa-de-pron%C3%B3sticos"><i class="fa fa-check"></i><b>7.4</b> Visualización Comparativa de Pronósticos</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="comparacion.html"><a href="comparacion.html#an%C3%A1lisis-visual"><i class="fa fa-check"></i><b>7.4.1</b> Análisis Visual</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="comparacion.html"><a href="comparacion.html#comparaci%C3%B3n-conceptual"><i class="fa fa-check"></i><b>7.5</b> Comparación Conceptual</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sarima" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">5</span> Modelado ARIMA: Metodología Box-Jenkins<a href="sarima.html#sarima" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Los modelos ARIMA (AutoRegressive Integrated Moving Average) representan una familia de modelos estadísticos para series temporales que capturan diferentes aspectos de la autocorrelación en los datos. Cuando la serie presenta estacionalidad, se extiende a SARIMA (Seasonal ARIMA), incorporando componentes estacionales adicionales.</p>
<p><strong>Nota</strong>: Los datos y el modelo SARIMA fueron preparados en el Capítulo <a href="preparacion.html#preparacion">2</a>. Los objetos <code>sarima_model</code>, <code>sarima_forecast</code>, <code>ts_train_regular</code>, <code>ts_test_regular</code> y las métricas están disponibles directamente.</p>
<div id="resumen-del-modelo-ajustado-1" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Resumen del Modelo Ajustado<a href="sarima.html#resumen-del-modelo-ajustado-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>## === MODELO SARIMA ===</code></pre>
<pre><code>## Partición de datos:</code></pre>
<pre><code>##   Entrenamiento: 1972-07 a 1997-12 | n = 290</code></pre>
<pre><code>##   Prueba: 1998-01 a 1998-12 | n = 12</code></pre>
<pre><code>## Orden identificado: SARIMA(3,0,0)(1,0,1)[12]</code></pre>
<pre><code>## Métricas de pronóstico (1998):</code></pre>
<pre><code>##   MAE: 4.067 mm</code></pre>
<pre><code>##   RMSE: 5.036 mm</code></pre>
<pre><code>##   MAPE: 383.01 %</code></pre>
<pre><code>##   Cobertura IC: 91.7 %</code></pre>
</div>
<div id="especificación-del-modelo-sarima" class="section level2 hasAnchor" number="5.2">
<h2><span class="header-section-number">5.2</span> Especificación del Modelo SARIMA<a href="sarima.html#especificaci%C3%B3n-del-modelo-sarima" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La metodología Box-Jenkins utiliza los criterios de información (AIC, AICc, BIC) para seleccionar el modelo óptimo. El modelo fue seleccionado automáticamente en el Capítulo <a href="preparacion.html#preparacion">2</a> evaluando sistemáticamente múltiples especificaciones SARIMA(p,d,q)(P,D,Q)[12].</p>
<p><strong>Notación del modelo SARIMA(p,d,q)(P,D,Q)[m]:</strong></p>
<ul>
<li><strong>p</strong>: Orden del componente autorregresivo (AR)</li>
<li><strong>d</strong>: Orden de diferenciación regular</li>
<li><strong>q</strong>: Orden del componente de media móvil (MA)</li>
<li><strong>P</strong>: Orden del componente autorregresivo estacional (SAR)</li>
<li><strong>D</strong>: Orden de diferenciación estacional</li>
<li><strong>Q</strong>: Orden del componente de media móvil estacional (SMA)</li>
<li><strong>m</strong>: Período estacional (12 para datos mensuales)</li>
</ul>
<pre><code>## === MODELO SELECCIONADO ===</code></pre>
<pre><code>## Series: ts_train_regular 
## ARIMA(3,0,0)(1,0,1)[12] with non-zero mean 
## Box Cox transformation: lambda= 0.3803753 
## 
## Coefficients:
##          ar1      ar2      ar3    sar1     sma1    mean
##       0.1564  -0.0233  -0.1372  0.8433  -0.6620  2.5399
## s.e.  0.0608   0.0610   0.0639  0.0720   0.0932  0.1649
## 
## sigma^2 = 2.23:  log likelihood = -525.91
## AIC=1065.81   AICc=1066.21   BIC=1091.5
## 
## Training set error measures:
##                    ME     RMSE      MAE  MPE MAPE      MASE        ACF1
## Training set 0.990914 4.568569 3.492013 -Inf  Inf 0.7630116 -0.04105949</code></pre>
<pre><code>## 
## === ESPECIFICACIÓN DEL MODELO ===</code></pre>
<pre><code>## Modelo seleccionado: SARIMA (3,0,0) (1,0,1)[12]</code></pre>
<pre><code>## Criterios de información:</code></pre>
<pre><code>##   AIC:   1065.81</code></pre>
<pre><code>##   AICc:  1066.21</code></pre>
<pre><code>##   BIC:   1091.5</code></pre>
<pre><code>## Varianza de los residuos (sigma^2): 2.2301</code></pre>
</div>
<div id="análisis-comparativo-serie-original-vs.-valores-ajustados" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Análisis Comparativo: Serie Original vs. Valores Ajustados<a href="sarima.html#an%C3%A1lisis-comparativo-serie-original-vs.-valores-ajustados" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="index_files/figure-html/comparacion-original-sarima-1.png" width="1152" /></p>
<pre><code>## 
## === CALIDAD DEL AJUSTE ===</code></pre>
<pre><code>## Correlación entre serie original y valores ajustados: 0.4133</code></pre>
<pre><code>## R² (porcentaje de varianza explicada): 17.08 %</code></pre>
<pre><code>## Error cuadrático medio (MSE) in-sample: 20.8718</code></pre>
<pre><code>## Raíz del error cuadrático medio (RMSE) in-sample: 4.569 mm</code></pre>
<p><strong>Interpretación del gráfico:</strong></p>
<ul>
<li><strong>Línea gris</strong>: Datos observados de precipitación mensual</li>
<li><strong>Línea roja</strong>: Valores ajustados por el modelo SARIMA</li>
</ul>
<p>El modelo captura exitosamente:
- Las variaciones interanuales de la precipitación
- La estructura de autocorrelación temporal</p>
<p>Las discrepancias entre ambas líneas representan los <strong>residuos</strong>, que idealmente deben comportarse como ruido blanco (sin patrón sistemático).</p>
</div>
<div id="interpretación-de-componentes-del-modelo" class="section level2 hasAnchor" number="5.4">
<h2><span class="header-section-number">5.4</span> Interpretación de Componentes del Modelo<a href="sarima.html#interpretaci%C3%B3n-de-componentes-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>## === INTERPRETACIÓN DE COMPONENTES ===</code></pre>
<pre><code>## AR(3): La serie depende de sus valores pasados recientes
##   Coeficientes AR: 0.1564 -0.0233 -0.1372</code></pre>
<pre><code>## No se requiere diferenciación regular (d=0): Serie ya estacionaria</code></pre>
<pre><code>## SAR(1): Dependencia con el mismo mes del año anterior
##   Coeficientes SAR: 0.8433 
## No se requiere diferenciación estacional (D=0)
## SMA(1): Efectos estacionales de shocks pasados
##   Coeficientes SMA: -0.662</code></pre>
<pre><code>## 
## === SIGNIFICANCIA ESTADÍSTICA ===</code></pre>
<pre><code>## 
## z test of coefficients:
## 
##            Estimate Std. Error z value  Pr(&gt;|z|)    
## ar1        0.156371   0.060804  2.5717   0.01012 *  
## ar2       -0.023333   0.060953 -0.3828   0.70186    
## ar3       -0.137233   0.063867 -2.1487   0.03166 *  
## sar1       0.843283   0.071972 11.7168 &lt; 2.2e-16 ***
## sma1      -0.661997   0.093238 -7.1001 1.247e-12 ***
## intercept  2.539898   0.164871 15.4054 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## 
## Interpretación: Coeficientes con p-valor &lt; 0.05 son estadísticamente significativos</code></pre>
</div>
<div id="diagnóstico-de-residuos" class="section level2 hasAnchor" number="5.5">
<h2><span class="header-section-number">5.5</span> Diagnóstico de Residuos<a href="sarima.html#diagn%C3%B3stico-de-residuos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Un buen modelo ARIMA debe producir residuos que se comporten como ruido blanco (sin autocorrelación, media cero, varianza constante, distribución normal).</p>
<p><img src="index_files/figure-html/diagnostico-residuos-sarima-1.png" width="1152" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(3,0,0)(1,0,1)[12] with non-zero mean
## Q* = 25.658, df = 19, p-value = 0.14
## 
## Model df: 5.   Total lags used: 24</code></pre>
<p><strong>Interpretación de los gráficos:</strong></p>
<ol style="list-style-type: decimal">
<li><strong>Residuos a lo largo del tiempo</strong>: Deben fluctuar aleatoriamente alrededor de cero sin patrones sistemáticos</li>
<li><strong>ACF de residuos</strong>: Todas las barras deben estar dentro de las bandas azules (no autocorrelación)</li>
<li><strong>Histograma</strong>: Debe aproximarse a una distribución normal centrada en cero</li>
</ol>
<pre><code>## === TESTS ESTADÍSTICOS DE RESIDUOS ===</code></pre>
<pre><code>## Test de Ljung-Box (autocorrelación):</code></pre>
<pre><code>##   Estadístico: 24.3565</code></pre>
<pre><code>##   P-valor: 0.2272</code></pre>
<pre><code>##   ✓ Conclusión: No hay autocorrelación significativa (p &gt; 0.05)
##     Los residuos se comportan como ruido blanco</code></pre>
<pre><code>## Test de Shapiro-Wilk (normalidad):</code></pre>
<pre><code>##   Estadístico W: 0.9852</code></pre>
<pre><code>##   P-valor: 0.0044</code></pre>
<pre><code>##   ⚠ Conclusión: Los residuos NO siguen distribución normal estricta (p &lt; 0.05)
##     Esto puede afectar la validez de los intervalos de confianza</code></pre>
<pre><code>## Estadísticas de residuos:</code></pre>
<pre><code>##   Media: -0.013 mm (ideal: ~0)</code></pre>
<pre><code>##   Desviación estándar: 1.48 mm</code></pre>
<pre><code>##   Rango: [ -4.53 , 3.35 ] mm</code></pre>
</div>
<div id="pronóstico-para-1998" class="section level2 hasAnchor" number="5.6">
<h2><span class="header-section-number">5.6</span> Pronóstico para 1998<a href="sarima.html#pron%C3%B3stico-para-1998" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Generamos el pronóstico para el año 1998 (12 meses) y comparamos con los valores observados.</p>
<p><img src="index_files/figure-html/pronostico-sarima-1.png" width="1152" /></p>
<p>Como se observa en el gráfico, el modelo SARIMA captura efectivamente el <strong>comportamiento estacional</strong> de la precipitación mensual en Cali, reproduciendo el <strong>patrón bimodal</strong> característico de la región con dos períodos de máxima precipitación en <strong>abril-mayo</strong> y <strong>octubre-noviembre</strong>, separados por períodos de menor precipitación. El pronóstico (línea roja) sigue de cerca la trayectoria de los valores observados.</p>
<p>La <strong>banda roja translúcida</strong> representa el intervalo de confianza al 95%, que cuantifica la incertidumbre inherente al pronóstico. Es notable que en algunos meses el intervalo es más amplio (mayor incertidumbre) que en otros, reflejando la variabilidad natural de la precipitación. La estructura del modelo SARIMA permite que esta incertidumbre se adapte a las características específicas de cada período.</p>
</div>
<div id="evaluación-del-desempeño-del-modelo-1" class="section level2 hasAnchor" number="5.7">
<h2><span class="header-section-number">5.7</span> Evaluación del Desempeño del Modelo<a href="sarima.html#evaluaci%C3%B3n-del-desempe%C3%B1o-del-modelo-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>## === MÉTRICAS DE DESEMPEÑO DEL PRONÓSTICO SARIMA ===</code></pre>
<pre><code>## Error Absoluto Medio (MAE): 4.067 mm</code></pre>
<pre><code>## Raíz del Error Cuadrático Medio (RMSE): 5.036 mm</code></pre>
<pre><code>## Error Porcentual Absoluto Medio (MAPE): 383.01 %</code></pre>
<pre><code>## Cobertura del intervalo de confianza (95%): 91.7 %</code></pre>
<pre><code>##   Observaciones dentro del IC: 11 de 12</code></pre>
<pre><code>## Test de Shapiro-Wilk (normalidad de errores de pronóstico):</code></pre>
<pre><code>##   Estadístico W: 0.9129</code></pre>
<pre><code>##   P-valor: 0.2325</code></pre>
<pre><code>##   Conclusión: Los errores siguen distribución normal (p &gt; 0.05)</code></pre>
<pre><code>## 
## === ESTADÍSTICAS DE ERRORES ===</code></pre>
<pre><code>## Media de errores: 2.352 mm</code></pre>
<pre><code>##   (Sesgo: valor cercano a 0 indica predicciones no sesgadas)</code></pre>
<pre><code>## Desviación estándar de errores: 4.651 mm</code></pre>
<pre><code>## Error mínimo: -4.107 mm</code></pre>
<pre><code>## Error máximo: 8.673 mm</code></pre>
<p><strong>Análisis de las métricas:</strong></p>
<p>El modelo SARIMA presenta un <strong>desempeño muy similar</strong> al de Holt-Winters, con métricas comparables:</p>
<ul>
<li><p><strong>MAE = 4.067 mm</strong>: Error absoluto medio prácticamente idéntico al de Holt-Winters (4.016 mm), con una diferencia de apenas 0.05 mm. Ambos modelos logran precisiones equivalentes.</p></li>
<li><p><strong>RMSE = 5.036 mm</strong>: Ligeramente superior al RMSE de Holt-Winters (4.585 mm), diferencia de 0.45 mm. La relación RMSE/MAE ≈ 1.24 confirma ausencia de errores atípicos extremos.</p></li>
<li><p><strong>Cobertura del IC = 91.7%</strong>: 11 de 12 observaciones dentro del IC 95%, ligeramente inferior a HW (100%) pero cercana a la cobertura teórica esperada.</p></li>
<li><p><strong>Normalidad (p = 0.2325)</strong>: Confirma distribución normal de errores, validando intervalos de confianza.</p></li>
<li><p><strong>Sesgo (media = 2.352 mm)</strong>: Leve subestimación, sin comprometer la calidad de pronósticos.</p></li>
</ul>
<p><strong>Conclusión:</strong> SARIMA presenta <strong>desempeño equivalente</strong> a Holt-Winters (MAE ≈ 4 mm). Ambas metodologías son igualmente apropiadas para pronósticos de precipitación en Cali. SARIMA ofrece <strong>fundamentación estadística rigurosa</strong> (Box-Jenkins) y modelado explícito de autocorrelación, mientras HW ofrece mayor simplicidad interpretativa.</p>
</div>
<div id="diagnóstico-de-errores-de-pronóstico" class="section level2 hasAnchor" number="5.8">
<h2><span class="header-section-number">5.8</span> Diagnóstico de Errores de Pronóstico<a href="sarima.html#diagn%C3%B3stico-de-errores-de-pron%C3%B3stico" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><img src="index_files/figure-html/diagnostico-errores-sarima-1.png" width="1152" /></p>
<p><strong>Interpretación de los diagnósticos:</strong></p>
<p>Los gráficos de diagnóstico de SARIMA muestran un comportamiento <strong>muy similar</strong> al observado en Holt-Winters, confirmando que ambos modelos capturan adecuadamente la estructura temporal de la serie:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Serie temporal de errores</strong>: Al igual que en Holt-Winters, los errores fluctúan aleatoriamente alrededor de cero sin tendencias sistemáticas. Ambos modelos extraen exitosamente la información predecible de la serie histórica.</p></li>
<li><p><strong>Distribución de errores (histograma)</strong>: Presenta simetría comparable a HW, con la media (línea azul) prácticamente coincidente con cero (línea roja), confirmando ausencia de sesgo en ambos modelos.</p></li>
<li><p><strong>Q-Q Plot</strong>: La alineación de puntos sobre la diagonal es similar en ambos modelos, validando normalidad aproximada. Pequeñas desviaciones en las colas son aceptables en muestras pequeñas (n=12).</p></li>
<li><p><strong>ACF de errores</strong>: <strong>Todas las barras están dentro de las bandas azules</strong> (límites al 95%), igual que en Holt-Winters. Esto confirma que tanto SARIMA como HW capturan completamente la autocorrelación temporal, dejando errores independientes.</p></li>
</ol>
<p><strong>Comparación entre modelos</strong>: Los diagnósticos de SARIMA y Holt-Winters son prácticamente idénticos, validando que ambas metodologías cumplen con los supuestos estadísticos fundamentales (residuos independientes, varianza constante, normalidad). No hay diferencias sustanciales en la calidad del ajuste entre ambos modelos para esta serie específica.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="holt-winters.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="prophet.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
